<?php
$options = array(
  'tab1' => array(
		'title' => __('General', '{domain}'),
		'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
		'type' => 'tab',
		'options' => array(
			'header-logo' => array(
				'type' => 'upload',
				'label' => __('Header Logo', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'general-background' => array(
				'type' => 'upload',
				'label' => __('General Background', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'footer-logo' => array(
				'type' => 'upload',
				'label' => __('Footer Logo', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'pages-header-background' => array(
				'type' => 'upload',
				'label' => __('Pages Header Background', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'phone' => array(
				'type' => 'text',
				'label' => __('Phone', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
      'fax' => array(
  			'type' => 'text',
  			'label' => __('FAX', '{domain}'),
  			'desc' => __('Option Description', '{domain}'),
  			'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
  			'help' => __('Some html that will appear in tip popup', '{domain}'),
  		),
			'mail' => array(
				'type' => 'text',
				'label' => __('Mail', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'address' => array(
				'type' => 'text',
				'label' => __('Address', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'footer-about-title' => array(
				'type' => 'text',
				'label' => __('Footer About Title', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'footer-about' => array(
				'type' => 'textarea',
				'label' => __('Footer About', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'copyrights' => array(
				'type' => 'textarea',
				'label' => __('Copyrights', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
		),
	),
	'tab2' => array(
		'title' => __('Social', '{domain}'),
		'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
		'type' => 'tab',
		'options' => array(
			'facebook' => array(
				'type' => 'text',
				'label' => __('facebook', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'instgram' => array(
				'type' => 'text',
				'label' => __('instgram', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'twitter' => array(
				'type' => 'text',
				'label' => __('twitter', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'youtube' => array(
				'type' => 'text',
				'label' => __('youtube', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'linked' => array(
				'type' => 'text',
				'label' => __('linked', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'googleplus' => array(
				'type' => 'text',
				'label' => __('googleplus', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
		),
	),
	'tab3' => array(
		'title' => __('About Page', '{domain}'),
		'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
		'type' => 'tab',
		'options' => array(
      'about-title' => array(
				'type' => 'text',
				'label' => __('About Title', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
      'about-text' => array(
				'type' => 'textarea',
				'label' => __('About Text', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
      'about-image' => array(
        'type' => 'upload',
        'label' => __('About Image', '{domain}'),
        'desc' => __('Option Description', '{domain}'),
        'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
        'help' => __('Some html that will appear in tip popup', '{domain}'),
      ),
      'pride-title' => array(
				'type' => 'text',
				'label' => __('Pride Title', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
      'pride-text' => array(
				'type' => 'textarea',
				'label' => __('Pride Text', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'pride-image' => array(
			'type' => 'upload',
			'label' => __('Pride Image', '{domain}'),
			'desc' => __('Option Description', '{domain}'),
			'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
			'help' => __('Some html that will appear in tip popup', '{domain}'),
		  ),
      'vision-title' => array(
				'type' => 'text',
				'label' => __('Our vision Title', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
      'vision-text' => array(
				'type' => 'textarea',
				'label' => __('Our vision Text', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'vision-image' => array(
			'type' => 'upload',
			'label' => __('Our vision Image', '{domain}'),
			'desc' => __('Option Description', '{domain}'),
			'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
			'help' => __('Some html that will appear in tip popup', '{domain}'),
		  ),
      'mission-title' => array(
				'type' => 'text',
				'label' => __('Our Mission Title', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
      'mission-text' => array(
				'type' => 'textarea',
				'label' => __('Our Mission Text', '{domain}'),
				'desc' => __('Option Description', '{domain}'),
				'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
				'help' => __('Some html that will appear in tip popup', '{domain}'),
			),
			'mission-image' => array(
			'type' => 'upload',
			'label' => __('Our Mission Image', '{domain}'),
			'desc' => __('Option Description', '{domain}'),
			'attr' => array('class' => 'custom-class', 'data-foo' => 'bar'),
			'help' => __('Some html that will appear in tip popup', '{domain}'),
		  ),
		),
	),
);
